CREATE TABLE PERSON (
      ID INT NOT NULL
    , FIRST_NAME VARCHAR(60) NOT NULL
    , LAST_NAME VARCHAR(40) NOT NULL
    , BIRTH_DATE DATE
    , DPT_ID INT
    , AGE INT
    , UNIQUE (FIRST_NAME, LAST_NAME)
    , PRIMARY KEY (ID)
);

CREATE TABLE DPT (
      ID_DPT INT NOT NULL
    , NAME_DPT VARCHAR(60) NOT NULL
    , AVG_SALARY INT
);