INSERT INTO PERSON (ID, FIRST_NAME, LAST_NAME, BIRTH_DATE) VALUES (1, 'Matt', 'White', '1970-05-13');
INSERT INTO PERSON (ID, FIRST_NAME, LAST_NAME, BIRTH_DATE) VALUES (2, 'Jack', 'Smith', '1983-11-28');
INSERT INTO PERSON (ID, FIRST_NAME, LAST_NAME, BIRTH_DATE) VALUES (3, 'Dean', 'Sims', '1992-02-03');
INSERT INTO PERSON (ID, FIRST_NAME, LAST_NAME, BIRTH_DATE) VALUES (4, 'Fil', 'Wood', '2001-08-19');
