INSERT INTO PERSON (ID, FIRST_NAME, LAST_NAME, BIRTH_DATE, DPT_ID, AGE) VALUES (1, 'Matt', 'White', '1970-05-13', 1, 29);
INSERT INTO PERSON (ID, FIRST_NAME, LAST_NAME, BIRTH_DATE, DPT_ID, AGE) VALUES (2, 'Jack', 'Smith', '1983-11-28', 3, 35);
INSERT INTO PERSON (ID, FIRST_NAME, LAST_NAME, BIRTH_DATE, DPT_ID, AGE) VALUES (3, 'Dean', 'Sims', '1992-02-03', 2, 48);
INSERT INTO PERSON (ID, FIRST_NAME, LAST_NAME, BIRTH_DATE, DPT_ID, AGE) VALUES (4, 'Fil', 'Wood', '2001-08-19', null, 18);

INSERT INTO DPT (ID_DPT, NAME_DPT, AVG_SALARY) VALUES (1, 'Audit', 18000);
INSERT INTO DPT (ID_DPT, NAME_DPT, AVG_SALARY) VALUES (2, 'Hr', 5000);
INSERT INTO DPT (ID_DPT, NAME_DPT, AVG_SALARY) VALUES (3, 'Marketing', 12000);

